site_name: kirigami
theme:
  name: material

# Page tree
nav:
  - Home: index.md
  - Tools: tools.md
  - JSON Tools: json_tools.md
  - Real World: realworld.md
  - Use case: usecase.md
  - Systems Thinking: systems_thinking.md
  
